# Generated by Django 4.2.5 on 2023-09-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain_url', models.URLField()),
                ('login_user', models.CharField(default='default_value_here', max_length=100)),
                ('login_password', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@gmail.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
