# Generated by Django 3.1.5 on 2023-09-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trust',
            old_name='users',
            new_name='user',
        ),
    ]
