# Generated by Django 4.2.5 on 2023-09-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_school_id_alter_trust_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='login_credentials',
            new_name='username',
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=100),
        ),
    ]
