# Generated by Django 4.2.5 on 2023-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_login_credentials_school_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=100),
        ),
    ]
