# Generated by Django 4.2.5 on 2023-09-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_school_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trust',
            name='authentication_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
