# Generated by Django 4.2.5 on 2023-09-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_trust_authentication_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='username',
            new_name='login_password',
        ),
        migrations.RemoveField(
            model_name='trust',
            name='authentication_token',
        ),
        migrations.AddField(
            model_name='school',
            name='login_user',
            field=models.CharField(default='default_value_here', max_length=100),
        ),
    ]
