# Generated by Django 4.2.5 on 2023-09-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
